name: TripAdvisor Scraper (Rotating Cities)

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Select city
        id: select_city
        run: |
          cities=( "Felougha Lebanon" "Batroun Lebanon" "Arz Lebanon" "Bcharri Lebanon" "Byblos Lebanon" "Beirut Lebanon" "Tripoli Lebanon" "Sidon Lebanon" "Tyre Lebanon")
          
          index=$(( (GITHUB_RUN_NUMBER - 1) % ${#cities[@]} ))
          
          echo "CITY_NAME=${cities[$index]}" >> $GITHUB_ENV
          echo "Selected city: ${cities[$index]}"

      - name: Run scraper
        run: python scrapers/tripadvisor.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: data-${{ env.CITY_NAME }}
          path: data/restaurants_with_reviews.csv
      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/restaurants_with_reviews.csv
          git commit -m "Update CSV for $CITY_NAME" || echo "No changes"
          git push origin main